service: secure-file-upload
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    BUCKET_NAME: s3-demo-bucket2026
    METADATA_TABLE: file-metadata-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - arn:aws:s3:::s3-demo-bucket2026/*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
          Resource: !GetAtt FileMetadataTable.Arn

functions:
  generateUploadUrl:
    handler: src/handlers/generateUploadUrl.handler
    events:
      - http:
          path: upload-url
          method: post
          cors:
            origins:
              - 'http://localhost:3000'
            headers:
              - 'Content-Type'
              - 'Authorization'
            allowCredentials: true

  processUploadedFile:
    handler: src/handlers/processUploadedFile.handler
    events:
      - s3:
          bucket: s3-demo-bucket2026
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: uploads/original/

  getDownloadUrl:
    handler: src/handlers/getDownloadUrl.handler
    events:
      - http:
          path: download
          method: get
          cors:
            origins:
              - 'http://localhost:3000'
            headers:
              - 'Content-Type'
              - 'Authorization'
            allowCredentials: true

  getFileMetadata:
    handler: src/handlers/getFileMetadata.handler
    events:
      - http:
          path: file-metadata
          method: get
          cors:
            origins:
              - 'http://localhost:3000'
            headers:
              - 'Content-Type'
              - 'Authorization'
            allowCredentials: true

resources:
  Resources:
    FileMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: file-metadata-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileId
            AttributeType: S
        KeySchema:
          - AttributeName: fileId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
